version: "3.9"
services:
  exlibris-web:
    build: ./
    container_name: exlibris-web
    depends_on:
      - exlibris-db
    entrypoint: [ "make", "wait-for-db", "run-prod" ]
    environment:
      DATABASE_URL: "postgresql://exlibris:exlibris@exlibris-db:5432/exlibris"
      MODE_DEBUG: 1
      PORT: 80
      PYTHONPATH: src
      SECRETS_DIR: /run/secrets
    image: exlibris-web
    ports:
      - "8888:80"
    restart: unless-stopped
  exlibris-db:
    container_name: exlibris-db
    environment:
      POSTGRES_USER: exlibris
      POSTGRES_PASSWORD: exlibris
      POSTGRES_DB: exlibris
    image: postgres:13.4-alpine
    ports:
      - "5555:5432"
    restart: unless-stopped
    volumes:
      - exlibris-volume:/var/lib/postgresql/data
  exlibris-dba:
    container_name: exlibris-dba
    image: adminer
    restart: unless-stopped
    ports:
      - "5556:8080"
    volumes:
      - exlibris-volume:/var/lib/postgresql/data
volumes:
  exlibris-volume:
    name: exlibris-volume
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=100m
